title : CX 10K Spine-Leaf Workshop
author: 'RAK - Confidential - For training purposes only'
copyright: 'Hewlett Packard Enterprise 2024'
logo: 'images/hpe-logo.png'

description: >-
  CX 10K Spine-Leaf Lab Guide

execute:
  execute_notebooks           : off

html:
  home_page_in_navbar         : true
  favicon                     : 'images/fav-icon-32.png'